"""empty message

Revision ID: 01ec546fe86e
Revises: da8165c750a4
Create Date: 2023-11-25 14:21:01.178983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ec546fe86e'
down_revision = 'da8165c750a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
