"""empty message

Revision ID: 0c2f28255e18
Revises: 530c58af80d6
Create Date: 2024-01-03 08:16:20.753082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2f28255e18'
down_revision = '530c58af80d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_level_1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wainting_time', sa.String(length=100), nullable=True))

    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiting_time', sa.String(length=100), nullable=True))

    with op.batch_alter_table('dps_level_3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiting_time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_level_3', schema=None) as batch_op:
        batch_op.drop_column('waiting_time')

    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.drop_column('waiting_time')

    with op.batch_alter_table('dps_level_1', schema=None) as batch_op:
        batch_op.drop_column('wainting_time')

    # ### end Alembic commands ###
