"""empty message

Revision ID: 14f3001ba4e2
Revises: d9c03d82dc4a
Create Date: 2023-11-28 00:26:05.234533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f3001ba4e2'
down_revision = 'd9c03d82dc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthtrusts_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('visitor_address', sa.String(length=100), nullable=False),
    sa.Column('visitor_postal_code', sa.String(length=100), nullable=True),
    sa.Column('postal_address', sa.String(length=100), nullable=False),
    sa.Column('postal_postal_code', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('general_info', sa.Text(), nullable=True),
    sa.Column('practical_info', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('health_trust_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['health_trust_id'], ['health_trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthtrusts_department')
    # ### end Alembic commands ###
