"""empty message

Revision ID: 2d8f7da1e199
Revises: f4c0a39c7025
Create Date: 2023-12-07 14:04:32.390078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8f7da1e199'
down_revision = 'f4c0a39c7025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_clinic', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
