"""empty message

Revision ID: 2de4f113cff4
Revises: 2fa8dd54834f
Create Date: 2023-11-27 21:16:25.205223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de4f113cff4'
down_revision = '2fa8dd54834f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.add_column(sa.Column('more_info', sa.Text(), nullable=True))
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('practical_info', sa.Text(), nullable=True))

    with op.batch_alter_table('dps_subdepartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('practical_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_subdepartment', schema=None) as batch_op:
        batch_op.drop_column('practical_info')
        batch_op.drop_column('general_info')

    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.drop_column('practical_info')
        batch_op.drop_column('general_info')

    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('more_info')

    # ### end Alembic commands ###
