"""empty message

Revision ID: 2fa8dd54834f
Revises: c8a25642d002
Create Date: 2023-11-27 21:02:01.071618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa8dd54834f'
down_revision = 'c8a25642d002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
