"""empty message

Revision ID: 3ad354cc5643
Revises: fe7f4279e9a0
Create Date: 2023-11-29 08:32:14.971957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad354cc5643'
down_revision = 'fe7f4279e9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
