"""empty message

Revision ID: 42a78cdc431e
Revises: a9b4a6e724e8
Create Date: 2023-11-21 10:12:15.001601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a78cdc431e'
down_revision = 'a9b4a6e724e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helse_personell', schema=None) as batch_op:
        batch_op.alter_column('profilbilde',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helse_personell', schema=None) as batch_op:
        batch_op.alter_column('profilbilde',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
