"""empty message

Revision ID: 4c6b7775e366
Revises: 3ad354cc5643
Create Date: 2023-11-29 11:35:22.088441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6b7775e366'
down_revision = '3ad354cc5643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_description', sa.Text(), nullable=True))
        batch_op.drop_column('treatment_descirption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_descirption', sa.TEXT(), nullable=True))
        batch_op.drop_column('treatment_description')

    # ### end Alembic commands ###
