"""empty message

Revision ID: 530c58af80d6
Revises: 2d8f7da1e199
Create Date: 2023-12-07 15:55:01.535082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530c58af80d6'
down_revision = '2d8f7da1e199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True))

        # Fjern kolonnene
        batch_op.drop_column('psychiatrist_id')
        batch_op.drop_column('general_practitioner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        # Legg til kolonnene igjen
        batch_op.add_column(sa.Column('general_practitioner_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('psychiatrist_id', sa.INTEGER(), nullable=True))

        # Fjern de nye kolonnene
        batch_op.drop_column('review_date')
        batch_op.drop_column('title')
    # ### end Alembic commands ###
