"""empty message

Revision ID: 53fdb8838d40
Revises: 
Create Date: 2023-11-25 18:11:42.446591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fdb8838d40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_practitioner_office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_trust',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('private_clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychiatric_emergency_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voluntary_organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district_psychiatric_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('health_trust_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['health_trust_id'], ['health_trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_practitioner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['general_practitioner_office.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychiatrist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['private_clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychologist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('profile_picture', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('self_report', sa.String(length=600), nullable=True),
    sa.Column('waiting_time', sa.String(length=100), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['private_clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dps_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dps_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_id'], ['district_psychiatric_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_practitioner_method',
    sa.Column('general_practitioner_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_practitioner_id'], ['general_practitioner.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.PrimaryKeyConstraint('general_practitioner_id', 'method_id')
    )
    op.create_table('general_practitioner_problem_area',
    sa.Column('general_practitioner_id', sa.Integer(), nullable=False),
    sa.Column('problem_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_practitioner_id'], ['general_practitioner.id'], ),
    sa.ForeignKeyConstraint(['problem_area_id'], ['problem_area.id'], ),
    sa.PrimaryKeyConstraint('general_practitioner_id', 'problem_area_id')
    )
    op.create_table('general_practitioner_services',
    sa.Column('general_practitioner_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_practitioner_id'], ['general_practitioner.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('general_practitioner_id', 'service_id')
    )
    op.create_table('general_practitioner_work_form',
    sa.Column('general_practitioner_id', sa.Integer(), nullable=False),
    sa.Column('work_form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_practitioner_id'], ['general_practitioner.id'], ),
    sa.ForeignKeyConstraint(['work_form_id'], ['work_form.id'], ),
    sa.PrimaryKeyConstraint('general_practitioner_id', 'work_form_id')
    )
    op.create_table('psychiatrist_method',
    sa.Column('psychiatrist_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['psychiatrist.id'], ),
    sa.PrimaryKeyConstraint('psychiatrist_id', 'method_id')
    )
    op.create_table('psychiatrist_problem_area',
    sa.Column('psychiatrist_id', sa.Integer(), nullable=False),
    sa.Column('problem_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_area_id'], ['problem_area.id'], ),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['psychiatrist.id'], ),
    sa.PrimaryKeyConstraint('psychiatrist_id', 'problem_area_id')
    )
    op.create_table('psychiatrist_services',
    sa.Column('psychiatrist_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['psychiatrist.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('psychiatrist_id', 'service_id')
    )
    op.create_table('psychiatrist_work_form',
    sa.Column('psychiatrist_id', sa.Integer(), nullable=False),
    sa.Column('work_form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['psychiatrist.id'], ),
    sa.ForeignKeyConstraint(['work_form_id'], ['work_form.id'], ),
    sa.PrimaryKeyConstraint('psychiatrist_id', 'work_form_id')
    )
    op.create_table('psychologist_method',
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologist.id'], ),
    sa.PrimaryKeyConstraint('psychologist_id', 'method_id')
    )
    op.create_table('psychologist_problem_area',
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('problem_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_area_id'], ['problem_area.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologist.id'], ),
    sa.PrimaryKeyConstraint('psychologist_id', 'problem_area_id')
    )
    op.create_table('psychologist_services',
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologist.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('psychologist_id', 'service_id')
    )
    op.create_table('psychologist_work_form',
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('work_form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologist.id'], ),
    sa.ForeignKeyConstraint(['work_form_id'], ['work_form.id'], ),
    sa.PrimaryKeyConstraint('psychologist_id', 'work_form_id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('psychiatrist_id', sa.Integer(), nullable=True),
    sa.Column('general_practitioner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_practitioner_id'], ['general_practitioner.id'], ),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['psychiatrist.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dps_subdepartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dps_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dps_subdepartment')
    op.drop_table('review')
    op.drop_table('psychologist_work_form')
    op.drop_table('psychologist_services')
    op.drop_table('psychologist_problem_area')
    op.drop_table('psychologist_method')
    op.drop_table('psychiatrist_work_form')
    op.drop_table('psychiatrist_services')
    op.drop_table('psychiatrist_problem_area')
    op.drop_table('psychiatrist_method')
    op.drop_table('general_practitioner_work_form')
    op.drop_table('general_practitioner_services')
    op.drop_table('general_practitioner_problem_area')
    op.drop_table('general_practitioner_method')
    op.drop_table('dps_department')
    op.drop_table('psychologist')
    op.drop_table('psychiatrist')
    op.drop_table('general_practitioner')
    op.drop_table('district_psychiatric_center')
    op.drop_table('voluntary_organization')
    op.drop_table('psychiatric_emergency_department')
    op.drop_table('private_clinic')
    op.drop_table('health_trust')
    op.drop_table('general_practitioner_office')
    op.drop_table('work_form')
    op.drop_table('service')
    op.drop_table('sector')
    op.drop_table('problem_area')
    op.drop_table('method')
    # ### end Alembic commands ###
