"""empty message

Revision ID: 5606067b5cbf
Revises: 203b011cff40
Create Date: 2023-11-26 09:24:32.515355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5606067b5cbf'
down_revision = '203b011cff40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatrist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('self_report', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('waiting_time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatrist', schema=None) as batch_op:
        batch_op.drop_column('waiting_time')
        batch_op.drop_column('self_report')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
