"""empty message

Revision ID: 67134d1d4427
Revises: 818b43aa6f18
Create Date: 2023-11-24 23:10:35.961986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67134d1d4427'
down_revision = '818b43aa6f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
