"""empty message

Revision ID: 791caa0b0f21
Revises: 
Create Date: 2023-11-23 08:05:27.594699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791caa0b0f21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbeidsform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beskrivelse', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beskrivelse', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problemomrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beskrivelse', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sektor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('helseforetak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('sektor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sektor_id'], ['sektor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privat_klinikk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('sektor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sektor_id'], ['sektor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distriktspsykiatrisk_senter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('helseforetak_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['helseforetak_id'], ['helseforetak.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psykiater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('tittel', sa.String(length=100), nullable=True),
    sa.Column('fødselsår', sa.Integer(), nullable=True),
    sa.Column('profilbilde', sa.LargeBinary(), nullable=True),
    sa.Column('Selvrapport', sa.String(length=600), nullable=True),
    sa.Column('klinikk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['klinikk_id'], ['privat_klinikk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psykolog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('tittel', sa.String(length=100), nullable=True),
    sa.Column('fødselsår', sa.Integer(), nullable=True),
    sa.Column('profilbilde', sa.LargeBinary(), nullable=True),
    sa.Column('Selvrapport', sa.String(length=600), nullable=True),
    sa.Column('klinikk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['klinikk_id'], ['privat_klinikk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avdeling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('dps_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_id'], ['distriktspsykiatrisk_senter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psykiater_arbeidsform',
    sa.Column('psykiater_id', sa.Integer(), nullable=False),
    sa.Column('arbeidsform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arbeidsform_id'], ['arbeidsform.id'], ),
    sa.ForeignKeyConstraint(['psykiater_id'], ['psykiater.id'], ),
    sa.PrimaryKeyConstraint('psykiater_id', 'arbeidsform_id')
    )
    op.create_table('psykiater_metode',
    sa.Column('psykiater_id', sa.Integer(), nullable=False),
    sa.Column('metode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metode_id'], ['metode.id'], ),
    sa.ForeignKeyConstraint(['psykiater_id'], ['psykiater.id'], ),
    sa.PrimaryKeyConstraint('psykiater_id', 'metode_id')
    )
    op.create_table('psykiater_problemomrade',
    sa.Column('psykiater_id', sa.Integer(), nullable=False),
    sa.Column('problemomrade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problemomrade_id'], ['problemomrade.id'], ),
    sa.ForeignKeyConstraint(['psykiater_id'], ['psykiater.id'], ),
    sa.PrimaryKeyConstraint('psykiater_id', 'problemomrade_id')
    )
    op.create_table('psykolog_arbeidsform',
    sa.Column('psykolog_id', sa.Integer(), nullable=False),
    sa.Column('arbeidsform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arbeidsform_id'], ['arbeidsform.id'], ),
    sa.ForeignKeyConstraint(['psykolog_id'], ['psykolog.id'], ),
    sa.PrimaryKeyConstraint('psykolog_id', 'arbeidsform_id')
    )
    op.create_table('psykolog_metode',
    sa.Column('psykolog_id', sa.Integer(), nullable=False),
    sa.Column('metode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metode_id'], ['metode.id'], ),
    sa.ForeignKeyConstraint(['psykolog_id'], ['psykolog.id'], ),
    sa.PrimaryKeyConstraint('psykolog_id', 'metode_id')
    )
    op.create_table('psykolog_problemomrade',
    sa.Column('psykolog_id', sa.Integer(), nullable=False),
    sa.Column('problemomrade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problemomrade_id'], ['problemomrade.id'], ),
    sa.ForeignKeyConstraint(['psykolog_id'], ['psykolog.id'], ),
    sa.PrimaryKeyConstraint('psykolog_id', 'problemomrade_id')
    )
    op.create_table('underavdeling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('avdeling_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avdeling_id'], ['avdeling.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('underavdeling')
    op.drop_table('psykolog_problemomrade')
    op.drop_table('psykolog_metode')
    op.drop_table('psykolog_arbeidsform')
    op.drop_table('psykiater_problemomrade')
    op.drop_table('psykiater_metode')
    op.drop_table('psykiater_arbeidsform')
    op.drop_table('avdeling')
    op.drop_table('psykolog')
    op.drop_table('psykiater')
    op.drop_table('distriktspsykiatrisk_senter')
    op.drop_table('privat_klinikk')
    op.drop_table('helseforetak')
    op.drop_table('sektor')
    op.drop_table('problemomrade')
    op.drop_table('metode')
    op.drop_table('arbeidsform')
    # ### end Alembic commands ###
