"""empty message

Revision ID: 818b43aa6f18
Revises: 92684aba4654
Create Date: 2023-11-24 22:58:21.402174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818b43aa6f18'
down_revision = '92684aba4654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('self_report', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('waiting_time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.drop_column('waiting_time')
        batch_op.drop_column('self_report')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
