"""empty message

Revision ID: 98e80b6dfe65
Revises: 14f3001ba4e2
Create Date: 2023-11-28 17:00:48.730744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e80b6dfe65'
down_revision = '14f3001ba4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dps_level_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('visitor_address', sa.String(length=100), nullable=False),
    sa.Column('postal_address', sa.String(length=100), nullable=False),
    sa.Column('general_info', sa.Text(), nullable=True),
    sa.Column('practical_info', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dps_level_3.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dps_level_3_problem_area',
    sa.Column('dps_level_3_id', sa.Integer(), nullable=False),
    sa.Column('problem_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_level_3_id'], ['dps_level_3.id'], ),
    sa.ForeignKeyConstraint(['problem_area_id'], ['problem_area.id'], ),
    sa.PrimaryKeyConstraint('dps_level_3_id', 'problem_area_id')
    )
    op.create_table('dps_level_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('by', sa.String(length=100), nullable=False),
    sa.Column('visitor_address', sa.String(length=100), nullable=False),
    sa.Column('postal_address', sa.String(length=100), nullable=False),
    sa.Column('general_info', sa.Text(), nullable=True),
    sa.Column('practical_info', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('dps_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_id'], ['district_psychiatric_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dps_level_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('visitor_address', sa.String(length=100), nullable=False),
    sa.Column('postal_address', sa.String(length=100), nullable=False),
    sa.Column('general_info', sa.Text(), nullable=True),
    sa.Column('practical_info', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dps_level_1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dps_level_2_method',
    sa.Column('dps_level_2_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_level_2_id'], ['dps_level_2.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.PrimaryKeyConstraint('dps_level_2_id', 'method_id')
    )
    op.create_table('dps_level_2_problem_area',
    sa.Column('dps_level_2_id', sa.Integer(), nullable=False),
    sa.Column('problem_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_level_2_id'], ['dps_level_2.id'], ),
    sa.ForeignKeyConstraint(['problem_area_id'], ['problem_area.id'], ),
    sa.PrimaryKeyConstraint('dps_level_2_id', 'problem_area_id')
    )
    op.create_table('dps_level_3_method',
    sa.Column('dps_level_2_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_level_2_id'], ['dps_level_2.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.PrimaryKeyConstraint('dps_level_2_id', 'method_id')
    )
    op.drop_table('dps_subdepartment_problem_area')
    op.drop_table('dps_department')
    op.drop_table('dps_subdepartment_method')
    op.drop_table('dps_subdepartment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dps_subdepartment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.Column('visitor_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('postal_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('general_info', sa.TEXT(), nullable=True),
    sa.Column('practical_info', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['dps_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dps_subdepartment_method',
    sa.Column('dps_subdepartment_id', sa.INTEGER(), nullable=False),
    sa.Column('method_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dps_subdepartment_id'], ['dps_subdepartment.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.PrimaryKeyConstraint('dps_subdepartment_id', 'method_id')
    )
    op.create_table('dps_department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('visitor_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('postal_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dps_id', sa.INTEGER(), nullable=False),
    sa.Column('general_info', sa.TEXT(), nullable=True),
    sa.Column('practical_info', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', sa.INTEGER(), nullable=True),
    sa.Column('by', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['dps_id'], ['district_psychiatric_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dps_subdepartment_problem_area',
    sa.Column('dps_subdepartment_id', sa.INTEGER(), nullable=False),
    sa.Column('problem_area_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dps_subdepartment_id'], ['dps_subdepartment.id'], ),
    sa.ForeignKeyConstraint(['problem_area_id'], ['problem_area.id'], ),
    sa.PrimaryKeyConstraint('dps_subdepartment_id', 'problem_area_id')
    )
    op.drop_table('dps_level_3_method')
    op.drop_table('dps_level_2_problem_area')
    op.drop_table('dps_level_2_method')
    op.drop_table('dps_level_2')
    op.drop_table('dps_level_1')
    op.drop_table('dps_level_3_problem_area')
    op.drop_table('dps_level_3')
    # ### end Alembic commands ###
