"""empty message

Revision ID: a9b4a6e724e8
Revises: 
Create Date: 2023-11-21 09:54:01.160519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b4a6e724e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behandlingsmetodikk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problemområde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tjeneste_niva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sektor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=50), nullable=False),
    sa.Column('tjeneste_niva_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tjeneste_niva_id'], ['tjeneste_niva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tjeneste_kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('sektor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sektor_id'], ['sektor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('helse_institusjon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('by', sa.String(length=200), nullable=True),
    sa.Column('profilbilde', sa.String(length=200), nullable=True),
    sa.Column('telefonnummer', sa.String(length=20), nullable=True),
    sa.Column('epost', sa.String(length=100), nullable=True),
    sa.Column('hjemmeside', sa.String(length=100), nullable=True),
    sa.Column('tjenestekategori_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tjenestekategori_id'], ['tjeneste_kategori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('helse_personell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('tittel', sa.String(length=100), nullable=True),
    sa.Column('kjønn', sa.String(length=100), nullable=True),
    sa.Column('fødselsår', sa.Integer(), nullable=True),
    sa.Column('Legelistelink', sa.String(length=100), nullable=True),
    sa.Column('Dinpsykologlink', sa.String(length=100), nullable=True),
    sa.Column('Selvrapport', sa.String(length=600), nullable=True),
    sa.Column('telefonnummer', sa.Integer(), nullable=True),
    sa.Column('epost', sa.String(length=100), nullable=True),
    sa.Column('profilbilde', sa.String(length=200), nullable=True),
    sa.Column('institusjon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institusjon_id'], ['helse_institusjon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anmeldelse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kommentar', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('personell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personell_id'], ['helse_personell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tjeneste_tilbud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pris', sa.Float(), nullable=True),
    sa.Column('ventetid', sa.String(length=100), nullable=True),
    sa.Column('personell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personell_id'], ['helse_personell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tjenestetilbud_behandlingsmetodikk',
    sa.Column('tjenestetilbud_id', sa.Integer(), nullable=False),
    sa.Column('behandlingsmetodikk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['behandlingsmetodikk_id'], ['behandlingsmetodikk.id'], ),
    sa.ForeignKeyConstraint(['tjenestetilbud_id'], ['tjeneste_tilbud.id'], ),
    sa.PrimaryKeyConstraint('tjenestetilbud_id', 'behandlingsmetodikk_id')
    )
    op.create_table('tjenestetilbud_format',
    sa.Column('tjenestetilbud_id', sa.Integer(), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['format.id'], ),
    sa.ForeignKeyConstraint(['tjenestetilbud_id'], ['tjeneste_tilbud.id'], ),
    sa.PrimaryKeyConstraint('tjenestetilbud_id', 'format_id')
    )
    op.create_table('tjenestetilbud_problemområde',
    sa.Column('tjenestetilbud_id', sa.Integer(), nullable=False),
    sa.Column('problemområde_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problemområde_id'], ['problemområde.id'], ),
    sa.ForeignKeyConstraint(['tjenestetilbud_id'], ['tjeneste_tilbud.id'], ),
    sa.PrimaryKeyConstraint('tjenestetilbud_id', 'problemområde_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tjenestetilbud_problemområde')
    op.drop_table('tjenestetilbud_format')
    op.drop_table('tjenestetilbud_behandlingsmetodikk')
    op.drop_table('tjeneste_tilbud')
    op.drop_table('anmeldelse')
    op.drop_table('helse_personell')
    op.drop_table('helse_institusjon')
    op.drop_table('tjeneste_kategori')
    op.drop_table('sektor')
    op.drop_table('tjeneste_niva')
    op.drop_table('problemområde')
    op.drop_table('format')
    op.drop_table('behandlingsmetodikk')
    # ### end Alembic commands ###
