"""empty message

Revision ID: b834cac2a6de
Revises: 839db52e28eb
Create Date: 2023-11-27 21:57:04.568872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b834cac2a6de'
down_revision = '839db52e28eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
