"""empty message

Revision ID: b95ee55f4e35
Revises: e69e4ef63418
Create Date: 2023-11-27 00:35:27.620197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95ee55f4e35'
down_revision = 'e69e4ef63418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dps_subdepartment_method',
    sa.Column('dps_subdepartment_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dps_subdepartment_id'], ['dps_subdepartment.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.PrimaryKeyConstraint('dps_subdepartment_id', 'method_id')
    )
    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('postal_address', sa.String(length=100), nullable=False))

    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('postal_address', sa.String(length=100), nullable=False))

    with op.batch_alter_table('dps_subdepartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('postal_address', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_subdepartment', schema=None) as batch_op:
        batch_op.drop_column('postal_address')
        batch_op.drop_column('visitor_address')

    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.drop_column('postal_address')
        batch_op.drop_column('visitor_address')

    with op.batch_alter_table('district_psychiatric_center', schema=None) as batch_op:
        batch_op.drop_column('postal_address')
        batch_op.drop_column('visitor_address')

    op.drop_table('dps_subdepartment_method')
    # ### end Alembic commands ###
