"""empty message

Revision ID: d9c03d82dc4a
Revises: 02c888cdd9d4
Create Date: 2023-11-27 22:32:35.172065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c03d82dc4a'
down_revision = '02c888cdd9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('by', sa.String(length=100), nullable=False))
        batch_op.drop_column('about')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.TEXT(), nullable=True))
        batch_op.drop_column('by')

    # ### end Alembic commands ###
