"""empty message

Revision ID: e69e4ef63418
Revises: d117de067dfa
Create Date: 2023-11-27 00:16:32.734065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69e4ef63418'
down_revision = 'd117de067dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    with op.batch_alter_table('dps_subdepartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_subdepartment', schema=None) as batch_op:
        batch_op.drop_column('about')

    with op.batch_alter_table('dps_department', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
