"""empty message

Revision ID: ecab3305c3c9
Revises: 01ec546fe86e
Create Date: 2023-11-25 14:24:06.484142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecab3305c3c9'
down_revision = '01ec546fe86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologist', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
