"""empty message

Revision ID: ed33515e8af5
Revises: 791caa0b0f21
Create Date: 2023-11-23 08:17:44.341653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed33515e8af5'
down_revision = '791caa0b0f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastlegekontor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('sektor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sektor_id'], ['sektor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frivillig_organisasjon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('sektor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sektor_id'], ['sektor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psykiatrisk_legevakt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('sektor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sektor_id'], ['sektor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fastlege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=100), nullable=False),
    sa.Column('kontor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kontor_id'], ['fastlegekontor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fastlege_arbeidsform',
    sa.Column('fastlege_id', sa.Integer(), nullable=False),
    sa.Column('arbeidsform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arbeidsform_id'], ['arbeidsform.id'], ),
    sa.ForeignKeyConstraint(['fastlege_id'], ['fastlege.id'], ),
    sa.PrimaryKeyConstraint('fastlege_id', 'arbeidsform_id')
    )
    op.create_table('fastlege_metode',
    sa.Column('fastlege_id', sa.Integer(), nullable=False),
    sa.Column('metode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fastlege_id'], ['fastlege.id'], ),
    sa.ForeignKeyConstraint(['metode_id'], ['metode.id'], ),
    sa.PrimaryKeyConstraint('fastlege_id', 'metode_id')
    )
    op.create_table('fastlege_problemomrade',
    sa.Column('fastlege_id', sa.Integer(), nullable=False),
    sa.Column('problemomrade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fastlege_id'], ['fastlege.id'], ),
    sa.ForeignKeyConstraint(['problemomrade_id'], ['problemomrade.id'], ),
    sa.PrimaryKeyConstraint('fastlege_id', 'problemomrade_id')
    )
    with op.batch_alter_table('avdeling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventetid', sa.String(length=100), nullable=True))

    with op.batch_alter_table('privat_klinikk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventetid', sa.String(length=100), nullable=True))

    with op.batch_alter_table('psykiater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventetid', sa.String(length=100), nullable=True))

    with op.batch_alter_table('psykolog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventetid', sa.String(length=100), nullable=True))

    with op.batch_alter_table('underavdeling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventetid', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underavdeling', schema=None) as batch_op:
        batch_op.drop_column('ventetid')

    with op.batch_alter_table('psykolog', schema=None) as batch_op:
        batch_op.drop_column('ventetid')

    with op.batch_alter_table('psykiater', schema=None) as batch_op:
        batch_op.drop_column('ventetid')

    with op.batch_alter_table('privat_klinikk', schema=None) as batch_op:
        batch_op.drop_column('ventetid')

    with op.batch_alter_table('avdeling', schema=None) as batch_op:
        batch_op.drop_column('ventetid')

    op.drop_table('fastlege_problemomrade')
    op.drop_table('fastlege_metode')
    op.drop_table('fastlege_arbeidsform')
    op.drop_table('fastlege')
    op.drop_table('psykiatrisk_legevakt')
    op.drop_table('frivillig_organisasjon')
    op.drop_table('fastlegekontor')
    # ### end Alembic commands ###
