"""empty message

Revision ID: fe7f4279e9a0
Revises: 98e80b6dfe65
Create Date: 2023-11-29 08:18:50.533250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7f4279e9a0'
down_revision = '98e80b6dfe65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dps_department')
    with op.batch_alter_table('dps_level_1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_description', sa.Text(), nullable=True))

    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_descirption', sa.Text(), nullable=True))

    with op.batch_alter_table('dps_level_3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dps_level_3', schema=None) as batch_op:
        batch_op.drop_column('treatment_description')

    with op.batch_alter_table('dps_level_2', schema=None) as batch_op:
        batch_op.drop_column('treatment_descirption')

    with op.batch_alter_table('dps_level_1', schema=None) as batch_op:
        batch_op.drop_column('treatment_description')

    op.create_table('dps_department',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('visitor_address', sa.TEXT(), nullable=True),
    sa.Column('postal_address', sa.TEXT(), nullable=True),
    sa.Column('dps_id', sa.INTEGER(), nullable=True),
    sa.Column('general_info', sa.TEXT(), nullable=True),
    sa.Column('practical_info', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('by', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
